### ISSUE TITLE
dist.zip does not work 

### ISSUE THREAD

**Issue by mihneaz** [iggyjoaquin/busy#8]
File is corrupted and without a _config.js_, it can't run in dev nor build a new dist. 
Can you provide a _config.js_ template?

**Comment by iggyjs** [comment]
Hey yeah thanks for reporting that, I'll be sure to try to push something up within the next two days.

**Comment by iggyjoaquin** [comment]
@mihneaz fixed.

**Comment by iggyjs** [comment]
@mihneaz Resolved!
